services:
  finanzas-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    container_name: finanzas-app
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bolsillo_app.rule=Host(`bolsillo.ktuche.com`)"
      - "traefik.http.routers.bolsillo_app.entrypoints=websecure"
      - "traefik.http.routers.bolsillo_app.tls.certresolver=mytlschallenge"
      - "traefik.http.services.bolsillo_app.loadbalancer.server.port=3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    networks:
      - n8n_default
networks:
  n8n_default:
    external: true
